admin:
    pattern: '/'
    package: admin

front:
    pattern: '/'
    package: front

user:
    pattern: '/'
    package: user

page:
    pattern: 'page'
    controller: 'Acme\Controller\Page\'
cover:
    pattern: 'cover'
    controller: 'Acme\Controller\Cover\'
