home:
    pattern: '/'
    controller: 'Front\Controller\Posts'
    variables:
        type: home

posts:
    pattern: 'page(/page)'
    controller: 'Front\Controller\Posts'
    variables:
        type: home

post_default:
    pattern: post/(id)-(alias)
    controller: 'Front\Controller\Post'
    requirements:
            id: \d+

static_default:
    pattern: static/(id)-(alias)
    controller: 'Front\Controller\Post'
    variables:
        type: static
    requirements:
            id: \d+

feed:
    pattern: feed
    controller: 'Front\Controller\Posts'
    variables:
        format: feed
