home:
    pattern: '/'
    controller: 'Front\Controller\Posts'

posts:
    pattern: 'page(/page)'
    controller: 'Front\Controller\Posts'

post_default:
    pattern: (id)-(alias)
    controller: 'Front\Controller\Post'

static:
    pattern: page/(id)-(alias)
    controller: 'Front\Controller\Static'
