dashboard:
    pattern: '/'
    controller: 'Admin\Controller\Posts'

# Statics
static:
    pattern: 'statics'
    controller: 'Admin\Controller\Posts'
    variables:
        type: static
        activeMenu: static

# Categories
categories:
    pattern: categories
    controller: 'Admin\Controller\Categories'
    variables:
        activeMenu: categories

category:
    pattern: category
    controller: 'Admin\Controller\Category'
    variables:
        activeMenu: categories

# Authors & Author
authors:
    pattern: authors
    controller: 'Admin\Controller\Authors'
    variables:
        activeMenu: authors

author:
    pattern: author(/id)
    controller: 'Admin\Controller\Author'
    variables:
        activeMenu: authors

# Blogs
blogs:
    pattern: blogs
    controller: 'Admin\Controller\Blogs'
    variables:
        activeMenu: blogs

blog:
    pattern: blog(/id)
    controller: 'Admin\Controller\Blog'
    variables:
        activeMenu: blogs

# Settings
settings:
    pattern: settings
    controller: 'Admin\Controller\Settings'
    variables:
        activeMenu: settings

switchblog:
    pattern: switchblog/(id)
    controller: 'Admin\Controller\Switchblog'
