dashboard:
    pattern: '/'
    controller: 'Admin\Controller\Posts'

static:
    pattern: 'statics'
    controller: 'Admin\Controller\Posts'
    variables:
        type: static
        activeMenu: static

categories:
    pattern: categories
    controller: 'Admin\Controller\Categories'
    variables:
        activeMenu: categories

category:
    pattern: category
    controller: 'Admin\Controller\Category'
    variables:
        activeMenu: categories

settings:
    pattern: settings
    controller: 'Admin\Controller\Settings'
    variables:
        activeMenu: settings

authors:
    pattern: authors
    controller: 'Admin\Controller\Authors'
    variables:
        activeMenu: authors

switchblog:
    pattern: switchblog/(id)
    controller: 'Admin\Controller\Switchblog'
