dashboard:
    pattern: '/'
    controller: 'Admin\Controller\Posts'
    variables:
        activeMenu: dashboard

posts:
    pattern: '/'
    controller: 'Admin\Controller\Posts'
    variables:
        activeMenu: dashboard

post:
    pattern: post(/id)
    controller: 'Admin\Controller\Post'

post_state_up:
    pattern: post/state/up/(id)
    controller: 'Admin\Controller\Post'
    action:
        '*': StateController
    variables:
        state: 1

post_state_down:
    pattern: post/state/down/(id)
    controller: 'Admin\Controller\Post'
    action:
        '*': StateController
    variables:
        state: 0

# Statics
static:
    pattern: 'statics'
    controller: 'Admin\Controller\Posts'
    variables:
        type: static
        activeMenu: static

# Categories
categories:
    pattern: categories
    controller: 'Admin\Controller\Categories'
    variables:
        activeMenu: categories

category:
    pattern: category(/id)
    controller: 'Admin\Controller\Category'
    variables:
        activeMenu: categories

# Authors & Author
authors:
    pattern: authors
    controller: 'Admin\Controller\Authors'
    variables:
        activeMenu: authors

author:
    pattern: author(/id)
    controller: 'Admin\Controller\Author'
    variables:
        activeMenu: authors

# Blogs
blogs:
    pattern: blogs
    controller: 'Admin\Controller\Blogs'
    variables:
        activeMenu: blogs

blog:
    pattern: blog(/id)
    controller: 'Admin\Controller\Blog'
    variables:
        activeMenu: blogs

# Settings
settings:
    pattern: settings
    controller: 'Admin\Controller\Settings'
    variables:
        activeMenu: settings

switchblog:
    pattern: switchblog/(id)
    controller: 'Admin\Controller\Switchblog'

#Profile
profile:
    pattern: profile
    controller: 'Admin\Controller\Profile'
