dashboard:
    pattern: '/'
    controller: 'Admin\Controller\Posts'
    variables:
        activeMenu: dashboard

posts:
    pattern: '/'
    controller: 'Admin\Controller\Posts'
    variables:
        activeMenu: dashboard

post:
    pattern: post(/id)
    controller: 'Admin\Controller\Post'
    variables:
        activeMenu: dashboard
        hideMenu: 1

post_state_up:
    pattern: post/state/up/(id)
    controller: 'Admin\Controller\Post'
    action:
        '*': StateController
    variables:
        state: 1

post_state_down:
    pattern: post/state/down/(id)
    controller: 'Admin\Controller\Post'
    action:
        '*': StateController
    variables:
        state: 0

# Statics
statics:
    pattern: 'statics'
    controller: 'Admin\Controller\Posts'
    variables:
        type: static
        activeMenu: static

static:
    pattern: static(/id)
    controller: 'Admin\Controller\Post'
    variables:
        type: static
        activeMenu: static
        hideMenu: 1

static_state_up:
    pattern: static/state/up/(id)
    controller: 'Admin\Controller\Post'
    action:
        '*': StateController
    variables:
        type: static
        state: 1

static_state_down:
    pattern: static/state/down/(id)
    controller: 'Admin\Controller\Post'
    action:
        '*': StateController
    variables:
        type: static
        state: 0

# Categories
categories:
    pattern: categories
    controller: 'Admin\Controller\Categories'
    variables:
        activeMenu: categories

category:
    pattern: category(/id)
    controller: 'Admin\Controller\Category'
    variables:
        activeMenu: categories

# Authors & Author
authors:
    pattern: authors
    controller: 'Admin\Controller\Authors'
    variables:
        activeMenu: authors

author:
    pattern: author(/id)
    controller: 'Admin\Controller\Author'
    variables:
        activeMenu: authors

find_authors:
    pattern: authors/find
    controller: 'Admin\Controller\Authors'
    action:
        '*': FindController

# Blogs
blogs:
    pattern: blogs
    controller: 'Admin\Controller\Blogs'
    variables:
        activeMenu: blogs

blog:
    pattern: blog(/id)
    controller: 'Admin\Controller\Blog'
    variables:
        activeMenu: blogs

# Settings
settings:
    pattern: settings
    controller: 'Admin\Controller\Settings'
    variables:
        activeMenu: settings

switchblog:
    pattern: switchblog/(id)
    controller: 'Admin\Controller\Switchblog'

#Profile
profile:
    pattern: profile
    controller: 'Admin\Controller\Profile'

profile_image:
    pattern: profile/image
    controller: 'Admin\Controller\Profile'
    action:
        post: ImageController
        delete: DelimgController

# Upload
upload:
    pattern: upload
    controller: 'Admin\Controller\Upload'
